# ========= system global ========== #
models:
    nextgpt:
        model_name: JOSIEv4o
        agent_name: DeepSpeedAgent

seed: 13
max_length: 512 # max length of the user input prompt
logging_step: 5
num_clip_tokens: 77
gen_emb_dim: 768
pretrained_ckpt_path: ../ckpt/pretrained_ckpt/

# ========= multimodal encoder ========== #
imagebind_version: huge
